apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applications.application-controller.github.io
spec:
  group: application-controller.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: applications
    singular: application
    kind: Application
    shortNames:
      - app
  validations:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            application:
              type: string
              maxLength: 31
            environment:
              type: string
            version:
              type: string
      anyOf:
        - required:
            - application
            - version
            - environment
  additionalPrinterColumns:
    - name: Environment
      type: string
      description: The environment in which the application lives
      jsonPath: .spec.environment
    - name: Version
      type: string
      description: The version of the application
      jsonPath: .spec.version
    - name: Config
      type: string
      description: The version of the last applied configuration
      jsonPath: .status.configVersion
    - name: Last Updated
      type: date
      format: date-time
      description: The time the application was last updated
      jsonPath: .status.lastUpdated
