apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.application-operator.github.io
spec:
  group: application-operator.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                application:
                  type: string
                  maxLength: 31
                environment:
                  type: string
                version:
                  type: string
          anyOf:
            required:
              - application
              - version
              - environment
  scope: Namespaced
  names:
    plural: applications
    singular: application
    kind: Application
    shortNames:
      - app
  additionalPrinterColumns:
    - name: Environment
      type: string
      description: The environment in which the application lives
      JSONPath: .spec.environment
    - name: Version
      type: string
      description: The version of the application
      JSONPath: .spec.version
    - name: Config
      type: string
      description: The version of the last applied configuration
      JSONPath: .status.configVersion
    - name: Last Updated
      type: date
      format: date-time
      description: The time the application was last updated
      JSONPath: .status.lastUpdated
